version: '3.8'

services:
  # PHP-FPM container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - PHP_OPCACHE=1
      - COMPOSER_ALLOW_SUPERUSER=1
    command: php-fpm

  # MySQL container
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsaggregatordb
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Nginx container (reverse proxy)
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"  # Expose port 80 in the container to port 8000 on the host
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
